list:
  - file: "AddPerm.jar"
    url: https://github.com/TORO-Server/addperm

  - file: "Armor_stand.jar"
    url: https://github.com/malken21/Minecraft_Armor_stand_Spigot

  - file: "ArmorStandEditor.jar"
    url: https://github.com/Wolfieheart/ArmorStandEditor

  - file: "Auto_message.jar"
    url: https://github.com/malken21/Minecraft_AutoMessage_Spigot

  - file: "BanPlayerSheet.jar"
    url: https://github.com/malken21/BanPlayerSheet

  - file: "BlocksHub.jar"
    url: https://github.com/SBPrime/BlocksHub

  - file: "BungeeGuard.jar"
    url: https://github.com/lucko/BungeeGuard

  - file: "ClickMinecart.jar"
    url: https://github.com/punipuni-3730/Click-to-Minecart

  - file: "ClockItemTimer.jar"
    url: https://github.com/malken21/ClockItemTimer

  - file: "ClockPlugin.jar"
    url: https://github.com/malken21/Minecraft_clock_Spigot

  - file: "CommandPanels.jar"
    url: https://github.com/rockyhawk64/CommandPanels

  - file: "DiscordSRV.jar"
    url: https://github.com/DiscordSRV/DiscordSRV

  - file: "Dispenser_FallingBlock.jar"
    url: https://github.com/malken21/Minecraft_DispenserFallingBlock_Spigot

  - file: "DispenserActions.jar"
    url: https://github.com/malken21/DispenserActions

  - file: "dynmap.jar"
    url: https://github.com/webbukkit/dynmap
    get: "Dynmap-.*-spigot\\.jar"

  - file: "Effect_GUI.jar"
    url: https://github.com/malken21/Minecraft_Effect_GUI_Spigot

  - file: "EssentialsX.jar"
    url: https://github.com/EssentialsX/Essentials
    get: "EssentialsX-.*\\.jar"

  - file: "EssentialsXChat.jar"
    url: https://github.com/EssentialsX/Essentials
    get: "EssentialsXChat-.*\\.jar"

  - file: "KillPotionDeathLog.jar"
    url: https://github.com/malken21/KillPotionDeathLog

  - file: "GSit.jar"
    url: https://github.com/Gecolay/GSit

  - file: "HideNametagCMD.jar"
    url: https://github.com/malken21/HideNametagCMD

  - file: "ImageOnMap.jar"
    url: https://github.com/zDevelopers/ImageOnMap

  - file: "InfinityDispense.jar"
    url: https://github.com/TORO-Server/InfinityDispense

  - file: "Lift.jar"
    url: https://github.com/croxis/Lift

  - file: "LunaChat.jar"
    url: https://github.com/mofucraft/LunaChat

  - file: "Multiverse-Core.jar"
    url: https://github.com/Multiverse/Multiverse-Core

  - file: "ProtocolLib.jar"
    url: https://github.com/dmulloy2/ProtocolLib

  - file: "Skills.jar"
    url: https://github.com/TORO-Server/Skills

  - file: "TeleportSpectator.jar"
    url: https://github.com/malken21/Minecraft_TeleportSpectator_Spigot

  - file: "TOROpassICsystem.jar"
    url: https://github.com/TORO-Server/TOROpassICsystem

  - file: "Tps_log.jar"
    url: https://github.com/malken21/TPS-Log

  - file: "Vault.jar"
    url: https://github.com/milkbowl/Vault

  - file: "Warn_KillPotion.jar"
    url: https://github.com/malken21/Minecraft_Warn_KillPotion_Spigot

  - file: "WorldEditSelectionVisualizer.jar"
    url: https://github.com/MrMicky-FR/WorldEditSelectionVisualizer

  - file: "WorldGuardExtraFlags.jar"
    url: https://github.com/aromaa/WorldGuardExtraFlags
